imports:
    - { resource: config_dev.yml }

parameters:
    sensio_hangman.word_length: 3

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
